// Language translations
const translations = {
    ja: {
        // Header
        'nav.features': '特徴',
        'nav.docs': 'ドキュメント',
        'nav.download': 'ダウンロード',
        
        // Hero Section
        'hero.title.main': '動画プレイヤーで世界最速の言語学習',
        'hero.subtitle': '単語の意味、文法、そして究極の視聴体験',
        'hero.badge.size': 'わずか10MB',
        'hero.badge.speed': '爆速起動',
        'hero.badge.free': '完全無料',
        'hero.cta.download': '今すぐダウンロード',
        'hero.cta.learn': '詳しく見る',
        
        // Subtitles Demo
        'subtitle.line1': '字幕1: Hello, World!',
        'subtitle.line2': '字幕2: こんにちは、世界！',
        'subtitle.line3': '字幕3: Hola, Mundo!',
        
        // Features Section
        'features.title': 'RX-01で外国語の学習が加速し続けてもう止まらない',
        'feature1.title': 'トリプル字幕表示',
        'feature1.desc': '最大3つまでの字幕を同時表示。.srtファイルをドロップするだけで簡単に読み込めます。多言語学習に最適。',
        'feature2.title': '瞬間辞書検索',
        'feature2.desc': '字幕内の単語を辞書・発音・文法サイトから一瞬で検索。100種類以上のサイトをプリセット。カスタマイズも自由自在。',
        'feature3.title': 'バレットタイムリープ',
        'feature3.desc': '聞き取れなかった瞬間を最大0.1倍速でスロー再生しながら0.3秒ずつ戻って何度も確認。語学学習はもちろん、マジックやダンスの一瞬の動きも逃さない。くわしく見たい場所のズームも対応。',
        'feature4.title': 'あらゆる形式に対応',
        'feature4.desc': 'mp4, webm, mkv, mov, mp3, wav, flacなど多様な形式をサポート。ローカルファイルもYouTube URLも再生可能。',
        'feature5.title': 'わずか10MBで爆速起動',
        'feature5.desc': 'OSネイティブスピードで瞬時に起動。シークバーホバーでプレビュー表示、豊富なショートカットキーで快適操作。',
        'feature6.title': 'ながら視聴に最適',
        'feature6.desc': 'Picture-in-Picture対応で、動画を見ながら他の作業も可能。マルチタスクを快適にサポート。',
        
        // Platforms Section
        'platforms.title': 'あらゆる環境で',
        'platform.windows': 'Windows版',
        'platform.mac': 'Mac版',
        'platform.visios': 'VisiOS版',
        'platform.visios.desc': 'Chrome拡張機能で動作',
        'platform.nyan8': 'Nyan-8版',
        'platform.nyan8.desc': '学習言語の外国人と一緒に動画を見れる。インストール不要',
        'platforms.note': '全バージョン、全機能が完全無料！広告も無し！',
        
        // Download Section
        'download.title': '今すぐ始めよう',
        'download.subtitle': 'RX-01 Playerで、新しい視聴体験を。初回起動時にWindowsとMacではセキュリティ警告が出ることがあります。',
        'download.install.link': 'インストール方法',
        'download.subtitle.suffix': 'も参照してください。',
        'download.windows': 'Windows版',
        'download.windows.info': 'v0.1.0 - 10MB - Windows 10/11',
        'download.mac': 'Mac版',
        'download.mac.info': 'v0.1.0 - 10MB - macOS 10.15+',
        'download.visios': 'VisiOS版を入手',
        'download.nyan8': 'Nyan-8版を使う',
        
        // Footer
        'footer.brand.desc': '次世代言語学習動画プレイヤー',
        'footer.product': 'プロダクト',
        'footer.features': '特徴',
        'footer.download': 'ダウンロード',
        'footer.docs': 'ドキュメント',
        'footer.support': 'サポート',
        'footer.install': 'インストール方法',
        'footer.contact': 'お問い合わせ',
        'footer.copyright': '© 2026 RX-01 Player. All rights reserved.',

        // Index Page
        'index.title': 'RX-01 Player - 次世代動画プレイヤー',
        
        // Docs Page
        'docs.title': 'ドキュメント',
        'docs.subtitle': 'RX-01 Playerの仕様と機能を詳しく解説します',
        'docs.nav.home': 'ホーム',
        'docs.nav.install': 'インストール方法',
        'docs.toc.title': '目次',
        'docs.toc.overview': '概要',
        'docs.toc.versions': 'バージョン比較',
        'docs.toc.formats': '対応ファイル形式',
        'docs.toc.features': '主な機能',
        'docs.toc.shortcuts': 'ショートカット',
        'docs.security.title': '初回起動時のセキュリティ警告について',
        'docs.security.desc1': 'Windows版とMac版のRX-01 Playerは、Microsoft StoreやApp Storeに登録されていないため、初回起動時にセキュリティ警告が表示されることがあります。',
        'docs.security.desc2': '安全に起動する方法を詳しく解説していますので、以下のリンクからご確認ください：',
        'docs.security.windows': 'Windows版のインストール方法',
        'docs.security.mac': 'Mac版のインストール方法',
        'docs.overview.title': '概要',
        'docs.overview.desc': 'RX-01 Playerは、語学学習と高度な動画分析に最適化された次世代動画プレイヤーです。わずか10MBの軽量設計ながら、強力な機能を備えています。',
        'docs.overview.features': '主な特徴',
        'docs.overview.feature1': '最大3つまでの字幕を同時表示',
        'docs.overview.feature2': '字幕から辞書・発音サイトへ瞬間検索',
        'docs.overview.feature3': 'バレットタイムリープ機能で超スロー再生中の巻き戻しも快適',
        'docs.overview.feature4': 'ホイール操作でマウスの位置を最大3倍ズームイン可能',
        'docs.overview.feature5': 'Picture-in-Picture対応',
        'docs.overview.feature6': '10MBの軽量設計で爆速起動',
        'docs.overview.feature7': '豊富なショートカットキー（右クリックでキーバインドの変更可能）',
        'docs.versions.title': 'バージョン比較',
        'docs.versions.desc': 'RX-01 Playerは、利用シーンに応じて4つのバージョンを提供しています。',
        'docs.version.windows': 'Windows版',
        'docs.version.mac': 'Mac版',
        'docs.version.visios': 'VisiOS版',
        'docs.version.nyan8': 'Nyan-8版',
        'docs.version.recommended': '推奨',
        'docs.version.web': 'Web',
        'docs.version.social': 'Social',
        'docs.version.windows.desc': 'デスクトップアプリケーションとして動作するネイティブ版です。',
        'docs.version.mac.desc': 'macOS向けのネイティブアプリケーション版です。',
        'docs.version.visios.desc': 'Chrome拡張機能「VisiOS」上で動作するブラウザ版です。',
        'docs.version.nyan8.desc': 'コミュニケーション機能を統合したブラウザ版です。',
        'docs.version.features': '特徴',
        'docs.version.windows.feat1': 'OSネイティブ動作で最高のパフォーマンス',
        'docs.version.windows.feat2': 'Windows 10/11に対応',
        'docs.version.windows.feat3': 'わずか10MBのインストールサイズ',
        'docs.version.windows.feat4': '全機能を完全サポート',
        'docs.version.mac.feat1': 'macOS最適化で快適動作',
        'docs.version.mac.feat2': 'macOS 10.15 Catalina以降に対応',
        'docs.version.mac.feat3': 'Apple Siliconネイティブサポート',
        'docs.version.mac.feat4': '約10MBの超軽量設計',
        'docs.version.mac.feat5': '全機能を完全サポート',
        'docs.version.visios.feat1': '１秒インストールでブラウザから利用',
        'docs.version.visios.feat2': 'タブやブックマークを視覚的に管理',
        'docs.version.visios.feat3': '他のWebアプリと連携して動作',
        'docs.version.visios.feat4': 'Chrome/Edge/Braveなど対応',
        'docs.version.visios.feat5': 'クロスプラットフォーム対応',
        'docs.version.visios.feat6': 'VisiOS拡張機能が必要',
        'docs.version.nyan8.feat1': '完全インストール不要でブラウザから即利用',
        'docs.version.nyan8.feat2': '他のユーザーとテキストメッセージ',
        'docs.version.nyan8.feat3': 'ビデオチャット機能搭載',
        'docs.version.nyan8.feat4': 'ボイスコール対応',
        'docs.version.nyan8.feat5': '動画を見ながら友達と会話',
        'docs.comparison.title': '機能比較表',
        'docs.comparison.feature': '機能',
        'docs.comparison.install': 'インストール',
        'docs.comparison.required': '必要',
        'docs.comparison.extension': '拡張機能',
        'docs.comparison.not.required': '不要',
        'docs.comparison.speed': '起動速度',
        'docs.comparison.speed.fast': '爆速',
        'docs.comparison.speed.light': '光速',
        'docs.comparison.speed.instant': '神速',
        'docs.comparison.browser': 'ブラウザ上で動作',
        'docs.comparison.triple': 'トリプル字幕機能',
        'docs.comparison.dictionary': '辞書サイト連携',
        'docs.comparison.bullet': 'バレットタイムリープ',
        'docs.comparison.zoom': 'ホイールで好きな箇所を3xズームイン',
        'docs.comparison.video.url': 'ビデオ/音楽URL再生',
        'docs.comparison.youtube': 'YouTube URL再生',
        'docs.comparison.local': 'ローカルビデオ/音楽ファイルの再生',
        'docs.comparison.association': '拡張子を関連付けてローカル再生',
        'docs.comparison.friends': 'ネイティブの友達',
        'docs.comparison.price': '価格',
        'docs.comparison.free': '無料',
        'docs.formats.title': '対応ファイル形式',
        'docs.formats.desc': 'RX-01 Playerは、幅広いメディアファイル形式に対応しています。',
        'docs.formats.video': '動画形式',
        'docs.formats.audio': '音楽形式',
        'docs.formats.subtitle': '字幕形式',
        'docs.formats.online': 'オンライン動画',
        'docs.formats.tip.title': '💡 動画ファイルの読み込み方法',
        'docs.formats.tip1': 'ドラッグ&ドロップでファイルを追加',
        'docs.formats.tip2': 'ファイル選択ダイアログから選択',
        'docs.formats.tip3': 'URLを直接入力して再生 (動画再生中のCtrl+Vや右クリックメニューからの貼り付けにも対応)',
        'docs.formats.tip4': '.srtファイルをドロップして字幕を追加（最大3つまで）',
        'docs.features.title': '主な機能',
        'docs.feature.triple.title': 'トリプル字幕表示',
        'docs.feature.triple.desc': '最大3つまでの字幕を同時に表示できます。.srtファイルをドロップするだけで簡単に読み込めます。',
        'docs.feature.triple.example': '使用例：英語学習で英語字幕、日本語字幕、発音記号を同時表示',
        'docs.feature.dict.title': '辞書連携機能',
        'docs.feature.dict.desc': '字幕内の単語や文章を、登録した辞書サイトや発音サイト、文法サイトから瞬時に検索できます。',
        'docs.feature.dict.item1': '100種類以上のサイトをプリセット',
        'docs.feature.dict.item2': 'カスタムサイトの追加が可能',
        'docs.feature.dict.item3': '単語選択して右クリックで検索',
        'docs.feature.dict.item4': '文全体や一部分だけを選択可能',
        'docs.feature.bullet.title': 'バレットタイムリープ',
        'docs.feature.bullet.desc': '聞き取れなかった部分をスロー再生で繰り返し確認できる機能です。',
        'docs.feature.bullet.item1': '0.1x～4.0xで速度調整（YouTube動画は0.25～2.0x）',
        'docs.feature.bullet.item2': '再生速度に応じた0.3～3秒の巻き戻しに対応してるので一瞬の動作の確認が簡単',
        'docs.feature.bullet.item3': '語学学習に最適',
        'docs.feature.bullet.item4': 'ダンスやマジックの動作確認にも有効',
        'docs.feature.cc.title': 'YouTubeのCCをダウンロード',
        'docs.feature.cc.desc': 'YouTube再生中、一時停止したら右上からいつでも字幕をダウンロード可能',
        'docs.feature.cc.item1': '再生中、字幕が必要になったら右上の.srtダウンロードボタンをクリック',
        'docs.feature.cc.item2': '欲しい言語の.srtをダウンロードして、プレイヤーにドロップするだけで字幕表示',
        'docs.feature.pip.title': 'Picture-in-Picture',
        'docs.feature.pip.desc': '動画を小窓で表示し、他の作業をしながら視聴できます。',
        'docs.feature.pip.item1': 'デスクトップ版・ブラウザ版で対応',
        'docs.feature.pip.item2': 'サイズ・位置を自由に調整',
        'docs.feature.preview.title': 'シークバープレビュー',
        'docs.feature.preview.desc': 'シークバーにマウスをホバーすると、その位置の映像をプレビュー表示します。',
        'docs.shortcuts.title': 'ショートカットキー',
        'docs.shortcuts.desc': '豊富なショートカットキーで快適に操作できます。ショートカットキーのキーバインディングは画面を右クリックして「設定」を選ぶといつでも変更可能です',
        'docs.shortcuts.playback': '再生制御',
        'docs.shortcuts.volume': '音量・速度',
        'docs.shortcuts.display': '表示',
        'docs.shortcuts.other': 'その他',
        'docs.shortcuts.play': '再生/一時停止',
        'docs.shortcuts.back': '3秒戻る（再生速度に応じて可変）',
        'docs.shortcuts.forward': '3秒進む（再生速度に応じて可変）',
        'docs.shortcuts.volume.up': '音量を上げる/下げる',
        'docs.shortcuts.mute': 'ミュート切替',
        'docs.shortcuts.speed': '再生速度を下げる/上げる',
        'docs.shortcuts.fullscreen': 'フルスクリーン切替',
        'docs.shortcuts.subtitle': '.srtの字幕表示切替',
        'docs.shortcuts.pip': 'Picture-in-Picture',
        'docs.shortcuts.esc': 'フルスクリーン解除',
        'docs.shortcuts.paste': 'コピー中の動画URLを貼り付けて再生',
        'docs.shortcuts.close': 'プレイヤーを閉じる（アプリ版限定）',
        
        // Install Page
        'install.title': 'インストール方法',
        'install.subtitle': 'RX-01 Playerを安全にインストールする方法を解説します',
        'install.toc.title': '目次',
        'install.toc.windows': 'Windows版のインストール方法',
        'install.toc.mac': 'Mac版のインストール方法',
        'install.notice.title': 'セキュリティ警告について',
        'install.notice.desc': 'RX-01 Playerは完全に安全なフリーソフトですが、有料のMicrosoft StoreやApp Storeに登録されていないため、初回起動時にセキュリティ警告が表示されることがあります。このページでは、警告を安全に回避してRX-01 Playerを起動する方法を解説します。',
        'install.windows.title': 'Windows版のインストール',
        'install.windows.step1.title': 'RX-01 Playerをダウンロード',
        'install.windows.step1.desc': '公式サイトからRX-01 Player for Windowsをダウンロードします。',
        'install.windows.step2.title': 'ファイルを実行',
        'install.windows.step2.desc': 'ダウンロードした RX-01.exe をダブルクリックして実行します。',
        'install.windows.step3.title': '「Windows によって PC が保護されました」警告の対処法',
        'install.windows.step3.desc': 'この警告は、Microsoft Storeに登録されていないアプリを実行しようとした時、初回だけ表示されます。RX-01 Playerは安全なソフトウェアですので、以下の手順で起動できます。',
        'install.windows.step3.substep1.title': '「詳細情報」をクリック',
        'install.windows.step3.substep1.desc': '警告画面に表示されている「詳細情報」というリンクをクリックします。',
        'install.windows.step3.substep2.title': '「実行」ボタンをクリック',
        'install.windows.step3.substep2.desc': '「詳細情報」をクリックすると、「実行」ボタンが表示されます。このボタンをクリックしてRX-01.exeファイルを実行します。',
        'install.windows.step3.tip.title': '💡 なぜこの警告が表示されるの？',
        'install.windows.step3.tip.desc': 'Windowsは、Microsoft Storeに登録されていないアプリや、デジタル署名がないアプリを実行する際に、この警告を表示します。RX-01 Playerは収益を得ないで個人開発されたフリーソフトのため、高額な署名証明書を購入していません。そのため、この警告が表示されますが、ソフトウェア自体は完全に安全です。',
        'install.windows.step4.title': 'ファイルの関連付け（任意）',
        'install.windows.step4.desc': '動画ファイルをダブルクリックした時に自動的にRX-01 Playerで開くように設定できます。この設定は任意ですが、設定しておくと毎回アプリを起動する手間が省けて便利です。',
        'install.windows.step4.substep1.title': '動画ファイルを右クリックしてプロパティを選ぶ',
        'install.windows.step4.substep1.desc': '関連付けたい動画ファイル（例：movie.mp4やvideo.mkvなど）を右クリックして、「プロパティ」をクリックします',
        'install.windows.step4.substep3.title': '「変更」ボタンをクリック',
        'install.windows.step4.substep3.desc': 'プロパティウィンドウが表示されたら、「変更」ボタンをクリックします。',
        'install.windows.step4.substep4.title': 'RX-01 Playerを選択',
        'install.windows.step4.substep4.desc': '「このファイルを開く方法を選んでください」ウィンドウが表示されます。リストから「RX-01 Player」を探してクリックし、「OK」ボタンを押します。',
        'install.windows.step4.substep4.tip.title': '💡 リストにRX-01 Playerが表示されない場合',
        'install.windows.step4.substep4.tip.desc': '一番下の方にある「このPCで別のアプリを探す」をクリックして、RX-01.exeを保存した場所から直接選択してください。',
        'install.windows.step4.substep5.title': '設定完了',
        'install.windows.step4.substep5.desc1': 'これで、同じ種類の動画ファイル（例：すべての.mp4ファイル）をダブルクリックすると、自動的にRX-01 Playerで開かれるようになります。',
        'install.windows.step4.substep5.desc2': '別のファイル形式も関連付けたい場合は、その形式のファイル（例：.mkvや.mp3ファイル）でも同じ手順を繰り返してください。',
        'install.windows.step4.tip.title': '🎯 ファイル関連付けのメリット',
        'install.windows.step4.tip.desc': 'ファイル関連付けを設定すると、動画ファイルをダブルクリックするだけでRX-01 Playerで動画を再生できるようになります。',
        'install.windows.troubleshoot.title': '🔧 トラブルシューティング',
        'install.windows.troubleshoot.q1': 'Q: ウイルス対策ソフトが反応する場合は？',
        'install.windows.troubleshoot.a1': 'A: 一部のウイルス対策ソフトが誤検知する場合があります。RX-01 Playerを除外リストに追加するか、一時的にリアルタイム保護を無効にしてインストールを完了してください。',
        'install.mac.title': 'Mac版のインストール',
        'install.mac.step1.title': 'RX-01 Playerをダウンロード',
        'install.mac.step1.desc': '公式サイトからRX-01 Player for Macをダウンロードします。',
        'install.mac.step2.title': 'DMGファイルを開く',
        'install.mac.step2.desc': 'ダウンロードした RX-01-Player.dmg をダブルクリックして開きます。',
        'install.mac.step3.title': 'アプリケーションフォルダにコピー',
        'install.mac.step3.desc': '表示されたウィンドウで、RX-01 Playerのアイコンをアプリケーションフォルダにドラッグ&ドロップします。',
        'install.mac.step4.title': '「開発元を確認できません」警告の対処法',
        'install.mac.step4.desc': 'MacOSのGatekeeper機能により、App Storeや認証された開発元以外のアプリを初めて開く際に警告が表示されます。以下の方法でRX-01 Playerを起動できます。',
        'install.mac.step4.substep.title': 'システム設定から許可する',
        'install.mac.step4.substep.step1': 'RX-01 Playerをダブルクリックして警告を表示させる',
        'install.mac.step4.substep.step2': '「システム設定」（または「システム環境設定」）を開く',
        'install.mac.step4.substep.step3': '「プライバシーとセキュリティ」をクリック',
        'install.mac.step4.substep.step4': '「セキュリティ」セクションで「このまま開く」ボタンをクリック',
        'install.mac.step4.substep.step5': '確認ダイアログで「開く」をクリック',
        'install.mac.step4.tip.title': '💡 なぜこの警告が表示されるの？',
        'install.mac.step4.tip.desc': 'MacOSは、App Storeまたは認証された開発元からダウンロードされたアプリ以外を実行する際に、この警告を表示します。Apple Developer Programへの登録と公証（Notarization）には高額な年間費用がかかるため、個人開発のフリーソフトでは対応していないことが多いです。RX-01 Playerは安全なフリーソフトですので、上記の方法で安心してご利用ください。',
        'install.mac.step5.title': 'インストール完了',
        'install.mac.step5.desc': '一度「開く」を許可すれば、次回からは通常通りダブルクリックだけで起動できます。',
        'install.mac.troubleshoot.title': '🔧 Macのトラブルシューティング',
        'install.mac.troubleshoot.q1': 'Q: 「このまま開く」ボタンが表示されない場合は？',
        'install.mac.troubleshoot.a1': 'A: 警告が表示されてから数分経過すると、ボタンが表示されなくなることがあります。その場合は、もう一度RX-01 Playerを起動して警告を表示させてから、すぐにシステム設定を開いてください。',
        'install.mac.troubleshoot.q2': 'Q: 「破損しているため開けません」と表示される場合は？',
        'install.mac.troubleshoot.a2': 'A: ダウンロードが不完全な可能性があります。以下をお試しください：',
        'install.mac.troubleshoot.a2.item1': 'RX-01 Playerを削除して、再度ダウンロード',
        'install.mac.troubleshoot.a2.item2': '別のブラウザでダウンロードを試す',
        'install.mac.troubleshoot.a2.item3': 'ターミナルで以下のコマンドを実行（上級者向け）：',
        'install.mac.troubleshoot.q3': 'Q: 古いMacOSで警告の表示が違う場合は？',
        'install.mac.troubleshoot.a3': 'A: MacOSのバージョンによって警告メッセージや設定画面の表示が異なる場合がありますが、基本的な手順は同じです。「セキュリティとプライバシー」または「プライバシーとセキュリティ」の設定で許可してください。古いMacOSの場合だと、.appファイルを右クリックして「開く」を選択するだけでOKな場合もあります。',
        'install.mac.stepex.title': 'Macでのファイルの関連付け（任意）',
        'install.mac.stepex.desc': '動画ファイルをダブルクリックした時に自動的にRX-01 Playerで開くように設定できます。この設定は任意ですが、設定しておくと毎回アプリを起動する手間が省けて便利です。',
        'install.mac.stepex.step1': '動画ファイルを右クリックして「情報を見る」を選ぶ',
        'install.mac.stepex.step1desc': '関連付けたい動画ファイル（例：movie.mp4やvideo.mkvなど）を右クリックして、「情報を見る」をクリックします',
        'install.mac.stepex.step2': '「すべてを変更」ボタンをクリック',
        'install.mac.stepex.step2desc': '「このアプリケーションで開く」のところをRX-01 Playerに変更して「すべてを変更」ボタンをクリックします。',
        'install.mac.stepex.tip.title': '💡 リストにRX-01 Playerが表示されない場合',
        'install.mac.stepex.tip.desc': '一番下の方にある「その他」をクリックして、RX-01.appを保存した場所（通常はアプリケーションフォルダ）から直接選択してください。',
        'install.mac.stepex.step3': '確認ダイアログで「続ける」をクリック',
        'install.mac.stepex.step3desc': '確認メッセージが表示されるので、「続ける」をクリックします。これで、この拡張子（.mp4など）のすべてのファイルがRX-01 Playerで開くようになります。',
        'install.mac.stepex.step4': '設定完了',
        'install.mac.stepex.step4desc': 'これで、同じ種類の動画ファイル（例：すべての.mp4ファイル）をダブルクリックすると、自動的にRX-01 Playerで開かれるようになります。',
        'install.mac.stepex.note': '別のファイル形式も関連付けたい場合は、その形式のファイル（例：.mkvや.mp3ファイル）でも同じ手順を繰り返してください。',
        'install.mac.stepex.benefit.title': '🎯 ファイル関連付けのメリット',
        'install.mac.stepex.benefit.desc': 'ファイル関連付けを設定すると、動画ファイルをダブルクリックするだけでRX-01 Playerで動画を再生できるようになります。',
        'install.safety.title': '🛡️ 安全性について',
        'install.safety.desc': 'RX-01 Playerはフリーソフトウェアです。以下の点をご確認ください：',
        'install.safety.item1': 'マルウェアやスパイウェアは一切含まれていません',
        'install.safety.item2': '個人情報の収集や送信は行いません',
        'install.safety.item3': '広告やバンドルソフトウェア、有料要素は一切ありません',
        'install.safety.item4': '私はNyan-8やVisiOSなど様々なプラットフォームをすでに運営しており、悪質なことをする利点がまるでありません。安全性は保証しますが、一般的なソフトウェアと同じで、ソフトウェアを使用したことによる責任を開発者側では一切負いかねますのでご了承ください。',
        'install.safety.note': '※ 必ずこの公式サイトからダウンロードしてください。非公式の第三者サイトからのダウンロードは危険です。',
        'install.quicklinks.title': '次のステップ',
        'install.quicklinks.docs.title': 'ドキュメント',
        'install.quicklinks.docs.desc': '使い方や機能を詳しく知る',
        'install.quicklinks.features.title': '主な機能一覧',
        'install.quicklinks.features.desc': 'RX-01の主な機能を確認',
        'install.quicklinks.support.title': 'サポート',
        'install.quicklinks.support.desc': '問題が解決しない場合'
    },
    en: {
        // Header
        'nav.features': 'Features',
        'nav.docs': 'Documentation',
        'nav.download': 'Download',
        
        // Hero Section
        'hero.title.main': 'World\'s Fastest Language Learning with Video Player',
        'hero.subtitle': 'Word meanings, grammar, and the ultimate viewing experience',
        'hero.badge.size': 'Only 10MB',
        'hero.badge.speed': 'Lightning Fast',
        'hero.badge.free': 'Completely Free',
        'hero.cta.download': 'Download Now',
        'hero.cta.learn': 'Learn More',
        
        // Subtitles Demo
        'subtitle.line1': 'Subtitle 1: Hello, World!',
        'subtitle.line2': 'Subtitle 2: こんにちは、世界！',
        'subtitle.line3': 'Subtitle 3: Hola, Mundo!',
        
        // Features Section
        'features.title': 'Accelerate Your Foreign Language Learning with RX-01',
        'feature1.title': 'Triple Subtitle Display',
        'feature1.desc': 'Display up to 3 subtitles simultaneously. Simply drag and drop .srt files to load them easily. Perfect for multilingual learning.',
        'feature2.title': 'Instant Dictionary Lookup',
        'feature2.desc': 'Search words in subtitles instantly from dictionary, pronunciation, and grammar sites. Over 100 preset sites. Fully customizable.',
        'feature3.title': 'Bullet Time Leap',
        'feature3.desc': 'Review missed moments in slow motion (0.1x speed) while rewinding 0.3 seconds at a time. Perfect for language learning, magic tricks, and dance movements. Zoom support included.',
        'feature4.title': 'Support for Major Formats',
        'feature4.desc': 'Supports various formats including mp4, webm, mkv, mov, mp3, wav, flac. Play both local files and YouTube URLs.',
        'feature5.title': 'Just 10MB with Lightning Fast Launch',
        'feature5.desc': 'Launches instantly at OS-native speed. Preview on seekbar hover, comfortable operation with rich keyboard shortcuts.',
        'feature6.title': 'Perfect for Multitasking',
        'feature6.desc': 'Picture-in-Picture support allows you to work on other tasks while watching videos. Comfortable multitasking support.',
        
        // Platforms Section
        'platforms.title': 'Available on All Platforms',
        'platform.windows': 'Windows',
        'platform.mac': 'Mac',
        'platform.visios': 'VisiOS',
        'platform.visios.desc': 'Works as Chrome extension',
        'platform.nyan8': 'Nyan-8',
        'platform.nyan8.desc': 'Watch videos with native speakers. No installation required',
        'platforms.note': 'All versions, all features completely free! No ads!',
        
        // Download Section
        'download.title': 'Get Started Now',
        'download.subtitle': 'New viewing experience with RX-01 Player. Security warnings may appear on first launch for Windows and Mac. Please refer to ',
        'download.install.link': 'Installation Guide',
        'download.subtitle.suffix': '.',
        'download.windows': 'Windows',
        'download.windows.info': 'v0.1.0 - 10MB - Windows 10/11',
        'download.mac': 'Mac',
        'download.mac.info': 'v0.1.0 - 10MB - macOS 10.15+',
        'download.visios': 'Get VisiOS Version',
        'download.nyan8': 'Use Nyan-8 Version',
        
        // Footer
        'footer.brand.desc': 'Next-Generation Language Learning Video Player',
        'footer.product': 'Product',
        'footer.features': 'Features',
        'footer.download': 'Download',
        'footer.docs': 'Documentation',
        'footer.support': 'Support',
        'footer.install': 'Installation',
        'footer.contact': 'Contact',
        'footer.copyright': '© 2026 RX-01 Player. All rights reserved.',
        
        // Index Page
        'index.title': 'RX-01 Player - Language Learning Video Player',

        // Docs Page
        'docs.title': 'Documentation',
        'docs.subtitle': 'Detailed explanation of RX-01 Player specifications and features',
        'docs.nav.home': 'Home',
        'docs.nav.install': 'Installation',
        'docs.toc.title': 'Table of Contents',
        'docs.toc.overview': 'Overview',
        'docs.toc.versions': 'Version Comparison',
        'docs.toc.formats': 'Supported File Formats',
        'docs.toc.features': 'Main Features',
        'docs.toc.shortcuts': 'Shortcuts',
        'docs.security.title': 'About Security Warnings on First Launch',
        'docs.security.desc1': 'Windows and Mac versions of RX-01 Player are not registered on Microsoft Store or App Store, so security warnings may appear on first launch.',
        'docs.security.desc2': 'Please refer to the following links for detailed instructions on how to safely launch:',
        'docs.security.windows': 'Windows Installation Guide',
        'docs.security.mac': 'Mac Installation Guide',
        'docs.overview.title': 'Overview',
        'docs.overview.desc': 'RX-01 Player is a next-generation video player optimized for language learning and advanced video analysis. Despite its lightweight 10MB design, it offers powerful features.',
        'docs.overview.features': 'Key Features',
        'docs.overview.feature1': 'Display up to 3 subtitles simultaneously',
        'docs.overview.feature2': 'Instant dictionary/pronunciation site search from subtitles',
        'docs.overview.feature3': 'Bullet Time Leap for comfortable rewinding during slow-motion playback',
        'docs.overview.feature4': 'Zoom up to 3x at any position with mouse wheel',
        'docs.overview.feature5': 'Picture-in-Picture support',
        'docs.overview.feature6': 'Lightning fast launch with 10MB design',
        'docs.overview.feature7': 'Rich keyboard shortcuts (customizable via right-click)',
        'docs.versions.title': 'Version Comparison',
        'docs.versions.desc': 'RX-01 Player offers 4 versions to suit different use cases.',
        'docs.version.windows': 'Windows',
        'docs.version.mac': 'Mac',
        'docs.version.visios': 'VisiOS',
        'docs.version.nyan8': 'Nyan-8',
        'docs.version.recommended': 'Recommended',
        'docs.version.web': 'Web',
        'docs.version.social': 'Social',
        'docs.version.windows.desc': 'Native desktop application version.',
        'docs.version.mac.desc': 'Native application for macOS.',
        'docs.version.visios.desc': 'Browser version running on VisiOS Chrome extension.',
        'docs.version.nyan8.desc': 'Browser version with integrated communication features.',
        'docs.version.features': 'Features',
        'docs.version.windows.feat1': 'Best performance with OS-native operation',
        'docs.version.windows.feat2': 'Compatible with Windows 10/11',
        'docs.version.windows.feat3': 'Only 10MB installation size',
        'docs.version.windows.feat4': 'Full feature support',
        'docs.version.mac.feat1': 'Comfortable operation optimized for macOS',
        'docs.version.mac.feat2': 'Compatible with macOS 10.15 Catalina or later',
        'docs.version.mac.feat3': 'Apple Silicon native support',
        'docs.version.mac.feat4': 'Ultra-lightweight 10MB design',
        'docs.version.mac.feat5': 'Full feature support',
        'docs.version.visios.feat1': '1-second installation, use from browser',
        'docs.version.visios.feat2': 'Visual management of tabs and bookmarks',
        'docs.version.visios.feat3': 'Works with other web apps',
        'docs.version.visios.feat4': 'Compatible with Chrome/Edge/Brave',
        'docs.version.visios.feat5': 'Cross-platform support',
        'docs.version.visios.feat6': 'Requires VisiOS extension',
        'docs.version.nyan8.feat1': 'No installation required, instant browser access',
        'docs.version.nyan8.feat2': 'Text messaging with other users',
        'docs.version.nyan8.feat3': 'Video chat feature',
        'docs.version.nyan8.feat4': 'Voice call support',
        'docs.version.nyan8.feat5': 'Chat with friends while watching videos',
        'docs.comparison.title': 'Feature Comparison',
        'docs.comparison.feature': 'Feature',
        'docs.comparison.install': 'Installation',
        'docs.comparison.required': 'Required',
        'docs.comparison.extension': 'Extension',
        'docs.comparison.not.required': 'Not Required',
        'docs.comparison.speed': 'Launch Speed',
        'docs.comparison.speed.fast': 'Blazing Fast',
        'docs.comparison.speed.light': 'Light Speed',
        'docs.comparison.speed.instant': 'Instant',
        'docs.comparison.browser': 'Runs in Browser',
        'docs.comparison.triple': 'Triple Subtitle',
        'docs.comparison.dictionary': 'Dictionary Integration',
        'docs.comparison.bullet': 'Bullet Time Leap',
        'docs.comparison.zoom': 'Wheel Zoom 3x Anywhere',
        'docs.comparison.video.url': 'Video/Audio URL Playback',
        'docs.comparison.youtube': 'YouTube URL Playback',
        'docs.comparison.local': 'Local Video/Audio File Playback',
        'docs.comparison.association': 'File Association for Local Playback',
        'docs.comparison.friends': 'Native Friends',
        'docs.comparison.price': 'Price',
        'docs.comparison.free': 'Free',
        'docs.formats.title': 'Supported File Formats',
        'docs.formats.desc': 'RX-01 Player supports a wide range of media file formats.',
        'docs.formats.video': 'Video Formats',
        'docs.formats.audio': 'Audio Formats',
        'docs.formats.subtitle': 'Subtitle Formats',
        'docs.formats.online': 'Online Videos',
        'docs.formats.tip.title': '💡 How to Load Video Files',
        'docs.formats.tip1': 'Drag & drop files to add',
        'docs.formats.tip2': 'Select from file dialog',
        'docs.formats.tip3': 'Enter URL directly (also supports Ctrl+V during playback or paste from right-click menu)',
        'docs.formats.tip4': 'Drop .srt files to add subtitles (up to 3)',
        'docs.features.title': 'Main Features',
        'docs.feature.triple.title': 'Triple Subtitle Display',
        'docs.feature.triple.desc': 'Display up to 3 subtitles simultaneously. Simply drag and drop .srt files to load them easily.',
        'docs.feature.triple.example': 'Example: Display English subtitles, Japanese subtitles, and phonetic symbols simultaneously for English learning',
        'docs.feature.dict.title': 'Dictionary Integration',
        'docs.feature.dict.desc': 'Instantly search words and sentences in subtitles from dictionary, pronunciation, and grammar sites.',
        'docs.feature.dict.item1': 'Over 100 preset sites',
        'docs.feature.dict.item2': 'Add custom sites',
        'docs.feature.dict.item3': 'Select words and right-click to search',
        'docs.feature.dict.item4': 'Select entire sentences or parts',
        'docs.feature.bullet.title': 'Bullet Time Leap',
        'docs.feature.bullet.desc': 'Review missed parts with slow-motion playback repeatedly.',
        'docs.feature.bullet.item1': 'Speed adjustment from 0.1x to 4.0x (YouTube: 0.25x to 2.0x)',
        'docs.feature.bullet.item2': 'Rewind 0.3 to 3 seconds according to playback speed for easy instant motion review',
        'docs.feature.bullet.item3': 'Perfect for language learning',
        'docs.feature.bullet.item4': 'Also effective for checking dance and magic moves',
        'docs.feature.cc.title': 'Download YouTube CC',
        'docs.feature.cc.desc': 'Download subtitles anytime from the top-right during YouTube playback when paused',
        'docs.feature.cc.item1': 'Click the .srt download button in the top-right when you need subtitles during playback',
        'docs.feature.cc.item2': 'Download .srt in your desired language and drop it into the player to display subtitles',
        'docs.feature.pip.title': 'Picture-in-Picture',
        'docs.feature.pip.desc': 'Display videos in a small window while working on other tasks.',
        'docs.feature.pip.item1': 'Available on desktop and browser versions',
        'docs.feature.pip.item2': 'Freely adjust size and position',
        'docs.feature.preview.title': 'Seekbar Preview',
        'docs.feature.preview.desc': 'Hover over the seekbar to preview the video at that position.',
        'docs.shortcuts.title': 'Keyboard Shortcuts',
        'docs.shortcuts.desc': 'Comfortable operation with rich keyboard shortcuts. Key bindings can be changed anytime by right-clicking the screen and selecting "Settings"',
        'docs.shortcuts.playback': 'Playback Control',
        'docs.shortcuts.volume': 'Volume & Speed',
        'docs.shortcuts.display': 'Display',
        'docs.shortcuts.other': 'Other',
        'docs.shortcuts.play': 'Play/Pause',
        'docs.shortcuts.back': 'Rewind 3 seconds (variable with playback speed)',
        'docs.shortcuts.forward': 'Forward 3 seconds (variable with playback speed)',
        'docs.shortcuts.volume.up': 'Increase/Decrease Volume',
        'docs.shortcuts.mute': 'Toggle Mute',
        'docs.shortcuts.speed': 'Decrease/Increase Speed',
        'docs.shortcuts.fullscreen': 'Toggle Fullscreen',
        'docs.shortcuts.subtitle': 'Toggle .srt Subtitle Display',
        'docs.shortcuts.pip': 'Picture-in-Picture',
        'docs.shortcuts.esc': 'Exit Fullscreen',
        'docs.shortcuts.paste': 'Paste and play copied video URL',
        'docs.shortcuts.close': 'Close Player (Desktop version only)',
        
        // Install Page
        'install.title': 'Installation Guide',
        'install.subtitle': 'Learn how to safely install RX-01 Player',
        'install.toc.title': 'Table of Contents',
        'install.toc.windows': 'Windows Installation',
        'install.toc.mac': 'Mac Installation',
        'install.notice.title': 'About Security Warnings',
        'install.notice.desc': 'RX-01 Player is completely safe free software, but because it is not registered on the paid Microsoft Store or App Store, security warnings may appear on first launch. This page explains how to safely bypass warnings and launch RX-01 Player.',
        'install.windows.title': 'Windows Installation',
        'install.windows.step1.title': 'Download RX-01 Player',
        'install.windows.step1.desc': 'Download RX-01 Player for Windows from the official website.',
        'install.windows.step2.title': 'Run the file',
        'install.windows.step2.desc': 'Double-click the downloaded RX-01.exe to run it.',
        'install.windows.step3.title': 'How to handle "Windows protected your PC" warning',
        'install.windows.step3.desc': 'This warning appears only on first launch when trying to run an app not registered on Microsoft Store. RX-01 Player is safe software, so you can launch it with the following steps.',
        'install.windows.step3.substep1.title': 'Click "More info"',
        'install.windows.step3.substep1.desc': 'Click the "More info" link displayed on the warning screen.',
        'install.windows.step3.substep2.title': 'Click "Run anyway" button',
        'install.windows.step3.substep2.desc': 'After clicking "More info", the "Run anyway" button will appear. Click this button to run the RX-01.exe file.',
        'install.windows.step3.tip.title': '💡 Why does this warning appear?',
        'install.windows.step3.tip.desc': 'Windows displays this warning when running apps not registered on Microsoft Store or apps without digital signatures. RX-01 Player is free software developed by an individual without revenue, so we have not purchased expensive signing certificates. Therefore this warning appears, but the software itself is completely safe.',
        'install.windows.step4.title': 'File Association (Optional)',
        'install.windows.step4.desc': 'You can set video files to automatically open with RX-01 Player when double-clicked. This setting is optional, but convenient as it saves the trouble of launching the app each time.',
        'install.windows.step4.substep1.title': 'Right-click video file and select Properties',
        'install.windows.step4.substep1.desc': 'Right-click the video file you want to associate (e.g., movie.mp4 or video.mkv) and click "Properties"',
        'install.windows.step4.substep3.title': 'Click "Change" button',
        'install.windows.step4.substep3.desc': 'When the Properties window appears, click the "Change" button.',
        'install.windows.step4.substep4.title': 'Select RX-01 Player',
        'install.windows.step4.substep4.desc': 'The "How do you want to open this file?" window will appear. Find "RX-01 Player" in the list, click it, and press the "OK" button.',
        'install.windows.step4.substep4.tip.title': '💡 If RX-01 Player is not shown in the list',
        'install.windows.step4.substep4.tip.desc': 'Click "Look for another app on this PC" at the bottom and directly select from where you saved RX-01.exe.',
        'install.windows.step4.substep5.title': 'Setup Complete',
        'install.windows.step4.substep5.desc1': 'Now, when you double-click the same type of video file (e.g., all .mp4 files), they will automatically open with RX-01 Player.',
        'install.windows.step4.substep5.desc2': 'If you want to associate other file formats, repeat the same steps with files of that format (e.g., .mkv or .mp3 files).',
        'install.windows.step4.tip.title': '🎯 Benefits of File Association',
        'install.windows.step4.tip.desc': 'With file association set up, you can play videos in RX-01 Player simply by double-clicking video files.',
        'install.windows.troubleshoot.title': '🔧 Troubleshooting',
        'install.windows.troubleshoot.q1': 'Q: What if antivirus software reacts?',
        'install.windows.troubleshoot.a1': 'A: Some antivirus software may give false positives. Add RX-01 Player to the exclusion list or temporarily disable real-time protection to complete installation.',
        'install.mac.title': 'Mac Installation',
        'install.mac.step1.title': 'Download RX-01 Player',
        'install.mac.step1.desc': 'Download RX-01 Player for Mac from the official website.',
        'install.mac.step2.title': 'Open DMG file',
        'install.mac.step2.desc': 'Double-click the downloaded RX-01-Player.dmg to open it.',
        'install.mac.step3.title': 'Copy to Applications folder',
        'install.mac.step3.desc': 'In the displayed window, drag and drop the RX-01 Player icon to the Applications folder.',
        'install.mac.step4.title': 'How to handle "Cannot verify developer" warning',
        'install.mac.step4.desc': 'Due to macOS Gatekeeper, a warning appears when first opening apps from sources other than App Store or authenticated developers. You can launch RX-01 Player using the following method.',
        'install.mac.step4.substep.title': 'Allow from System Settings',
        'install.mac.step4.substep.step1': 'Double-click RX-01 Player to display the warning',
        'install.mac.step4.substep.step2': 'Open "System Settings" (or "System Preferences")',
        'install.mac.step4.substep.step3': 'Click "Privacy & Security"',
        'install.mac.step4.substep.step4': 'Click "Open Anyway" button in the "Security" section',
        'install.mac.step4.substep.step5': 'Click "Open" in the confirmation dialog',
        'install.mac.step4.tip.title': '💡 Why does this warning appear?',
        'install.mac.step4.tip.desc': 'macOS displays this warning when running apps other than those from App Store or authenticated developers. Registration with Apple Developer Program and Notarization involves high annual costs, so many individual free software don\'t support it. RX-01 Player is safe free software, so you can use it with confidence using the above method.',
        'install.mac.step5.title': 'Installation Complete',
        'install.mac.step5.desc': 'Once you allow "Open", you can launch it normally with just a double-click from next time.',
        'install.mac.troubleshoot.title': '🔧 Mac Troubleshooting',
        'install.mac.troubleshoot.q1': 'Q: What if "Open Anyway" button is not displayed?',
        'install.mac.troubleshoot.a1': 'A: The button may not appear after several minutes have passed since the warning. In that case, launch RX-01 Player again to display the warning, then immediately open System Settings.',
        'install.mac.troubleshoot.q2': 'Q: What if "damaged and can\'t be opened" is displayed?',
        'install.mac.troubleshoot.a2': 'A: The download may be incomplete. Try the following:',
        'install.mac.troubleshoot.a2.item1': 'Delete RX-01 Player and download again',
        'install.mac.troubleshoot.a2.item2': 'Try downloading with a different browser',
        'install.mac.troubleshoot.a2.item3': 'Run the following command in Terminal (for advanced users):',
        'install.mac.troubleshoot.q3': 'Q: What if the warning looks different on older macOS?',
        'install.mac.troubleshoot.a3': 'A: Warning messages and settings screens may vary by macOS version, but the basic steps are the same. Allow it in "Security & Privacy" or "Privacy & Security" settings. With older macOS, simply right-clicking the .app file and selecting "Open" may work.',
        'install.mac.stepex.title': 'File Association on Mac (Optional)',
        'install.mac.stepex.desc': 'You can set video files to automatically open with RX-01 Player when double-clicked. This setting is optional, but convenient as it saves the trouble of launching the app each time.',
        'install.mac.stepex.step1': 'Right-click video file and select "Get Info"',
        'install.mac.stepex.step1desc': 'Right-click the video file you want to associate (e.g., movie.mp4 or video.mkv) and click "Get Info"',
        'install.mac.stepex.step2': 'Click "Change All" button',
        'install.mac.stepex.step2desc': 'Change "Open with" to RX-01 Player and click the "Change All" button.',
        'install.mac.stepex.tip.title': '💡 If RX-01 Player is not shown in the list',
        'install.mac.stepex.tip.desc': 'Click "Other" at the bottom and directly select from where you saved RX-01.app (usually the Applications folder).',
        'install.mac.stepex.step3': 'Click "Continue" in confirmation dialog',
        'install.mac.stepex.step3desc': 'A confirmation message will appear. Click "Continue". Now all files with this extension (such as .mp4) will open with RX-01 Player.',
        'install.mac.stepex.step4': 'Setup Complete',
        'install.mac.stepex.step4desc': 'Now, when you double-click the same type of video file (e.g., all .mp4 files), they will automatically open with RX-01 Player.',
        'install.mac.stepex.note': 'If you want to associate other file formats, repeat the same steps with files of that format (e.g., .mkv or .mp3 files).',
        'install.mac.stepex.benefit.title': '🎯 Benefits of File Association',
        'install.mac.stepex.benefit.desc': 'With file association set up, you can play videos in RX-01 Player simply by double-clicking video files.',
        'install.safety.title': '🛡️ About Safety',
        'install.safety.desc': 'RX-01 Player is free software. Please confirm the following:',
        'install.safety.item1': 'Contains no malware or spyware',
        'install.safety.item2': 'No personal information is collected or transmitted',
        'install.safety.item3': 'No ads, bundled software, or paid elements',
        'install.safety.item4': 'I already operate various platforms such as Nyan-8 and VisiOS, and there is no benefit to doing anything malicious. While I guarantee safety, as with general software, we cannot assume any responsibility for the use of the software.',
        'install.safety.note': '* Please download only from this official website. Downloading from unofficial third-party sites is dangerous.',
        'install.quicklinks.title': 'Next Steps',
        'install.quicklinks.docs.title': 'Documentation',
        'install.quicklinks.docs.desc': 'Learn how to use and features in detail',
        'install.quicklinks.features.title': 'Main Features List',
        'install.quicklinks.features.desc': 'Check RX-01\'s main features',
        'install.quicklinks.support.title': 'Support',
        'install.quicklinks.support.desc': 'If the problem is not resolved'
    }
};

// Language manager
const LanguageManager = {
    currentLang: 'ja',
    
    // Detect browser language
    detectLanguage() {
        const browserLang = navigator.language || navigator.userLanguage;
        return browserLang.startsWith('ja') ? 'ja' : 'en';
    },
    
    // Get stored language or detect
    getLanguage() {
        const stored = localStorage.getItem('rx01-lang');
        if (stored && (stored === 'ja' || stored === 'en')) {
            return stored;
        }
        return this.detectLanguage();
    },
    
    // Set language
    setLanguage(lang) {
        if (lang !== 'ja' && lang !== 'en') return;
        this.currentLang = lang;
        localStorage.setItem('rx01-lang', lang);
        document.documentElement.lang = lang;
        this.updatePageContent();
        this.updateLanguageSelector();
    },
    
    // Get translation
    t(key) {
        return translations[this.currentLang][key] || key;
    },
    
    // Update all page content
    updatePageContent() {
        document.querySelectorAll('[data-i18n]').forEach(element => {
            const key = element.getAttribute('data-i18n');
            const translation = this.t(key);
            
            if (element.tagName === 'INPUT' || element.tagName === 'TEXTAREA') {
                element.placeholder = translation;
            } else {
                element.textContent = translation;
            }
        });
        
        // Update HTML attributes
        document.querySelectorAll('[data-i18n-html]').forEach(element => {
            const key = element.getAttribute('data-i18n-html');
            element.innerHTML = this.t(key);
        });
    },
    
    // Update language selector
    updateLanguageSelector() {
        const selector = document.getElementById('language-selector');
        if (selector) {
            selector.value = this.currentLang;
        }
    },
    
    // Initialize
    init() {
        this.currentLang = this.getLanguage();
        document.documentElement.lang = this.currentLang;
        
        // Wait for DOM to be ready
        if (document.readyState === 'loading') {
            document.addEventListener('DOMContentLoaded', () => {
                this.updatePageContent();
                this.updateLanguageSelector();
            });
        } else {
            this.updatePageContent();
            this.updateLanguageSelector();
        }
    }
};

// Initialize on load
LanguageManager.init();
